### ISSUE TITLE
Is this lib work with react native ?

### ISSUE THREAD

**Issue by dukizwe** [matallui/artico#12]

**Comment by matallui** [comment]
Yes, it should work with React Native. There is an example of an Expo app in the repository. I will also plan to add some documentation on the topic.

**Comment by dukizwe** [comment]
Wow cool! Is this suitable for large-scale applications ??

**Comment by matallui** [comment]
No really sure what that means or how to answer that! I guess it's up to you. If you're using WebRTC, this library is simply an abstraction over that. If you need to scale the signaling, you can implement your own signaling a d plug it into Artico.

Artico Rooms won't scale though, since it's all P2P. If you need a solution to scale like that, you might want to take a look at Mediasoup or similar solutions.
