### ISSUE TITLE
Unable to assign custom ID to peer while using @rtco/server

### ISSUE THREAD

**Issue by AnupamKris** [matallui/artico#19]
Not able to assign custom ID while using custom signalling server

Server code
```js
import { ArticoServer } from "@rtco/server";

const server = new ArticoServer();
server.listen(5000);
```

Client Code
```js
const rtco = new Artico({
  id: "a789sdfgt",
  signaling: new SocketSignaling({
    url: "http://localhost:5000",
  }),
});
```

It is still connecting to a random id.

**Comment by matallui** [comment]
@AnupamKris I just took a look at the code. What you want do do should work if you replace that client code with:

```ts
const rtco = new Artico({
  signaling: new SocketSignaling({
    url: "http://localhost:5000",
    id: "a789sdfgt",
  }),
});
```

`Artico` itself doesn't care about the ID, it simply passes it down to the `SocketSignaling` (if no `signalling` is provided). In your case, since you're passing a custom one, it just uses that instead and the `id` you pass to `Artico` has no use. Does that make sense?

**Comment by AnupamKris** [comment]
I see.. It does make sense..
